import { FastifyInstance } from "fastify";
import Activite from "./activite";
import ActiviteCI from "./activiteCI";
import Agent from "./agent";
import AgentSession from "./agentSession";
import Approvisionnement from "./approvisionnement";
import Attribution from "./attribution";
import AttributionCaisse from "./attributionCaisse";
import BonMission from "./bonMission";
import Caisse from "./caisse";
import CategorieAgent from "./categorieAgent";
import CentreImputation from "./centreImputation";
import Compte from "./compte";
import ConfigurationSchema from "./configurationSchema";
import Delegation from "./delegation";
import DepartArrive from "./departArrive";
import Example from "./example";
import Exploitation from "./exploitation";
import File from "./file";
import Fonction from "./fonction";
import GrilleFrais from "./grilleFrais";
import GrilleKilometrique from "./grilleKilometrique";
import ItineraireDistance from "./itineraireDistance";
import Justification from "./justification";
import Mission from "./mission";
import MoyenTransport from "./moyenTransport";
import Nature from "./nature";
import NatureCompte from "./natureCompte";
import Numbon from "./numbon";
import Organisation from "./organisation";
import Poste from "./poste";
import Profil from "./profil";
import Referencedata from "./referencedata";
import Reversement from "./reversement";
import Role from "./role";
import SchemaComptable from "./schemaComptable";
import Societe from "./societe";
import TypeCarburant from "./typeCarburant";
import TypeFrais from "./typeFrais";
import TypeMission from "./typeMission";
import User from "./user";
import UserPriority from "./userPriority";
import UserSession from "./userSession";
import Ville from "./ville";
import ZoneIntervention from "./zoneIntervention";
export default function (server: FastifyInstance) {
    server.register(Activite, { prefix: "/activites" });
    server.register(ActiviteCI, { prefix: "/activiteCIs" });
    server.register(Agent, { prefix: "/agents" });
    server.register(AgentSession, { prefix: "/agentSessions" });
    server.register(Approvisionnement, { prefix: "/approvisionnements" });
    server.register(Attribution, { prefix: "/attributions" });
    server.register(AttributionCaisse, { prefix: "/attributionCaisses" });
    server.register(BonMission, { prefix: "/bonMissions" });
    server.register(Caisse, { prefix: "/caisses" });
    server.register(CategorieAgent, { prefix: "/categorieAgents" });
    server.register(CentreImputation, { prefix: "/centreImputations" });
    server.register(Compte, { prefix: "/comptes" });
    server.register(ConfigurationSchema, { prefix: "/configurationSchemas" });
    server.register(Delegation, { prefix: "/delegations" });
    server.register(DepartArrive, { prefix: "/departArrives" });
    server.register(Example, { prefix: "/examples" });
    server.register(Exploitation, { prefix: "/exploitations" });
    server.register(File, { prefix: "/files" });
    server.register(Fonction, { prefix: "/fonctions" });
    server.register(GrilleFrais, { prefix: "/grilleFraiss" });
    server.register(GrilleKilometrique, { prefix: "/grilleKilometriques" });
    server.register(ItineraireDistance, { prefix: "/itineraireDistances" });
    server.register(Justification, { prefix: "/justifications" });
    server.register(Mission, { prefix: "/missions" });
    server.register(MoyenTransport, { prefix: "/moyenTransports" });
    server.register(Nature, { prefix: "/natures" });
    server.register(NatureCompte, { prefix: "/natureComptes" });
    server.register(Numbon, { prefix: "/numbons" });
    server.register(Organisation, { prefix: "/organisation" });
    server.register(Poste, { prefix: "/postes" });
    server.register(Profil, { prefix: "/profils" });
    server.register(Referencedata, { prefix: "/referencedata" });
    server.register(Reversement, { prefix: "/reversements" });
    server.register(Role, { prefix: "/role" });
    server.register(SchemaComptable, { prefix: "/schemaComptables" });
    server.register(Societe, { prefix: "/societe" });
    server.register(TypeCarburant, { prefix: "/typeCarburants" });
    server.register(TypeFrais, { prefix: "/typeFraiss" });
    server.register(TypeMission, { prefix: "/typeMissions" });
    server.register(User, { prefix: "/user" });
    server.register(UserPriority, { prefix: "/userPrioritys" });
    server.register(UserSession, { prefix: "/userSessions" });
    server.register(Ville, { prefix: "/villes" });
    server.register(ZoneIntervention, { prefix: "/zoneInterventions" });
}